name: $(Build.SourceBranch)-$(Build.SourceVersion)-$(Rev:r)

resources:
  repositories:
  - repository: self

variables:
- template: .build/automation/variables.yml

trigger:
  batch: false
  branches:
    include:
    - main

pr:
  - main

stages:

  - template: .build/automation/stages/validate.yml
