# Makefile.include
# FSpot wide helper

# Directories

## Links

## Build

CSC_FLAGS = -debug
CSC = $(MCS) $(CSC_FLAGS) -target:exe
CSC_LIB = $(MCS) $(CSC_FLAGS) -target:library

## Runtime

MONO_DEBUGFLAGS = --debug
RUNTIME = mono $(MONO_DEBUGFLAGS)
