// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace GtkBeans {

	using System;
	using System.Runtime.InteropServices;

#region Autogenerated code
	public enum BuilderError {

		InvalidTypeFunction,
		UnhandledTag,
		MissingAttribute,
		InvalidAttribute,
		InvalidTag,
		MissingPropertyValue,
		InvalidValue,
		VersionMismatch,
	}
#endregion
}
