// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace Gnome.Vfs {

	using System;

#region Autogenerated code
	public enum DeviceType {

		Unknown,
		AudioCd,
		VideoDvd,
		Harddrive,
		Cdrom,
		Floppy,
		Zip,
		Jaz,
		Nfs,
		Autofs,
		Camera,
		MemoryStick,
		Smb,
		Apple,
		MusicPlayer,
		Windows,
		Loopback,
		Network,
	}
#endregion
}
