// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace Gnome.Vfs {

	using System;

	public delegate void DriveDisconnectedHandler(object o, DriveDisconnectedArgs args);

	public class DriveDisconnectedArgs : GLib.SignalArgs {
		public Gnome.Vfs.Drive Drive{
			get {
				return (Gnome.Vfs.Drive) Args[0];
			}
		}

	}
}
