// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace Gnome.Vfs {

	using System;


	[Flags]
#region Autogenerated code
	public enum FileInfoOptions {

		Default,
		GetMimeType = 1 << 0,
		ForceFastMimeType = 1 << 1,
		ForceSlowMimeType = 1 << 2,
		FollowLinks = 1 << 3,
		GetAccessRights = 1 << 4,
	}
#endregion
}
