// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace Gnome.Vfs {

	using System;


	[Flags]
#region Autogenerated code
	public enum FileInfoFields {

		None,
		Type = 1 << 0,
		Permissions = 1 << 1,
		Flags = 1 << 2,
		Device = 1 << 3,
		Inode = 1 << 4,
		LinkCount = 1 << 5,
		Size = 1 << 6,
		BlockCount = 1 << 7,
		IoBlockSize = 1 << 8,
		Atime = 1 << 9,
		Mtime = 1 << 10,
		Ctime = 1 << 11,
		SymlinkName = 1 << 12,
		MimeType = 1 << 13,
		Access = 1 << 14,
	}
#endregion
}
