// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace Gnome.Vfs {

	using System;


	[Flags]
#region Autogenerated code
	public enum FilePermissions {

		Suid = 1 << 11,
		Sgid = 1 << 10,
		Sticky = 1 << 9,
		UserRead = 1 << 8,
		UserWrite = 1 << 7,
		UserExec = 1 << 6,
		UserAll = UserRead | UserWrite | UserExec,
		GroupRead = 1 << 5,
		GroupWrite = 1 << 4,
		GroupExec = 1 << 3,
		GroupAll = GroupRead | GroupWrite | GroupExec,
		OtherRead = 1 << 2,
		OtherWrite = 1 << 1,
		OtherExec = 1,
		OtherAll = OtherRead | OtherWrite | OtherExec,
		AccessReadable = 1 << 16,
		AccessWritable = 1 << 17,
		AccessExecutable = 1 << 18,
	}
#endregion
}
