// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace Gnome.Vfs {

	using System;


	[Flags]
#region Autogenerated code
	public enum FileFlags {

		None,
		Symlink = 1 << 0,
		Local = 1 << 1,
	}
#endregion
}
