// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace Gnome.Vfs {

	using System;
	using System.Collections;
	using System.Runtime.InteropServices;

#region Autogenerated code
	[StructLayout(LayoutKind.Sequential)]
	public struct MimeAction {

		public Gnome.Vfs.MimeActionType ActionType;
		private IntPtr _component;
		private IntPtr _dummy_component;
		private IntPtr _application;

		public Gnome.Vfs.MimeApplication application {
			get { return Gnome.Vfs.MimeApplication.New (_application); }
		}
		private IntPtr _reserved1;

		public static Gnome.Vfs.MimeAction Zero = new Gnome.Vfs.MimeAction ();

		public static Gnome.Vfs.MimeAction New(IntPtr raw) {
			if (raw == IntPtr.Zero) {
				return Gnome.Vfs.MimeAction.Zero;
			}
			Gnome.Vfs.MimeAction self = new Gnome.Vfs.MimeAction();
			self = (Gnome.Vfs.MimeAction) Marshal.PtrToStructure (raw, self.GetType ());
			return self;
		}

		[DllImport("gnomevfs-2")]
		static extern int gnome_vfs_mime_action_launch_with_env(ref Gnome.Vfs.MimeAction raw, IntPtr uris, string envp);

		public Gnome.Vfs.Result LaunchWithEnv(GLib.List uris, string envp) {
			int raw_ret = gnome_vfs_mime_action_launch_with_env(ref this, uris.Handle, envp);
			Gnome.Vfs.Result ret = (Gnome.Vfs.Result) raw_ret;
			return ret;
		}

		[DllImport("gnomevfs-2")]
		static extern int gnome_vfs_mime_action_launch(ref Gnome.Vfs.MimeAction raw, IntPtr uris);

		public Gnome.Vfs.Result Launch(GLib.List uris) {
			int raw_ret = gnome_vfs_mime_action_launch(ref this, uris.Handle);
			Gnome.Vfs.Result ret = (Gnome.Vfs.Result) raw_ret;
			return ret;
		}

		[DllImport("gnomevfs-2")]
		static extern void gnome_vfs_mime_action_free(ref Gnome.Vfs.MimeAction raw);

		public void Free() {
			gnome_vfs_mime_action_free(ref this);
		}

		private static GLib.GType GType {
			get { return GLib.GType.Pointer; }
		}
#endregion
	}
}
