// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace Gnome.Vfs {

	using System;


	[Flags]
#region Autogenerated code
	public enum ModuleCallbackFullAuthenticationFlags {

		PreviousAttemptFailed = 1 << 0,
		NeedPassword = 1 << 1,
		NeedUsername = 1 << 2,
		NeedDomain = 1 << 3,
		SavingSupported = 1 << 4,
	}
#endregion
}
