// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace GtkSharp.GnomeVfsSharp {

	public class ObjectManager {

		static bool initialized = false;
		// Call this method from the appropriate module init function.
		public static void Initialize ()
		{
			if (initialized)
				return;

			initialized = true;
			GLib.ObjectManager.RegisterType("GnomeVFSVolumeMonitor", "Gnome.Vfs.VolumeMonitor,gnome-vfs-sharp");
			GLib.ObjectManager.RegisterType("GnomeVFSDrive", "Gnome.Vfs.Drive,gnome-vfs-sharp");
			GLib.ObjectManager.RegisterType("GnomeVFSMIMEMonitor", "Gnome.Vfs.MimeMonitor,gnome-vfs-sharp");
			GLib.ObjectManager.RegisterType("GnomeVFSVolume", "Gnome.Vfs.Volume,gnome-vfs-sharp");
		}
	}
}
