// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace Gnome.Vfs {

	using System;


	[Flags]
#region Autogenerated code
	public enum OpenMode {

		None,
		Read = 1 << 0,
		Write = 1 << 1,
		Random = 1 << 2,
	}
#endregion
}
