// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace Gnome.Vfs {

	using System;


	[Flags]
#region Autogenerated code
	public enum SetFileInfoMask {

		None,
		Name = 1 << 0,
		Permissions = 1 << 1,
		Owner = 1 << 2,
		Time = 1 << 3,
	}
#endregion
}
