// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace Gnome.Vfs {

	using System;


	[Flags]
#region Autogenerated code
	public enum UriHideOptions {

		None,
		UserName = 1 << 0,
		Password = 1 << 1,
		HostName = 1 << 2,
		HostPort = 1 << 3,
		ToplevelMethod = 1 << 4,
		FragmentIdentifier = 1 << 8,
	}
#endregion
}
