// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace Gnome.Vfs {

	using System;

#region Autogenerated code
	public enum XferErrorMode {

		Abort,
		Query = 1,
	}
#endregion
}
