// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace Gnome.Vfs {

	using System;


	[Flags]
#region Autogenerated code
	public enum XferOptions {

		Default,
		Unused1 = 1 << 0,
		FollowLinks = 1 << 1,
		Unused2 = 1 << 2,
		Recursive = 1 << 3,
		Samefs = 1 << 4,
		DeleteItems = 1 << 5,
		EmptyDirectories = 1 << 6,
		NewUniqueDirectory = 1 << 7,
		Removesource = 1 << 8,
		UseUniqueNames = 1 << 9,
		LinkItems = 1 << 10,
		FollowLinksRecursive = 1 << 11,
	}
#endregion
}
