// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace Gnome.Vfs {

	using System;
	using System.Collections;
	using System.Runtime.InteropServices;

#region Autogenerated code
	[StructLayout(LayoutKind.Sequential)]
	public struct XferProgressInfo {

		public Gnome.Vfs.XferProgressStatus Status;
		public Gnome.Vfs.Result VfsStatus;
		public Gnome.Vfs.XferPhase Phase;
		public string SourceName;
		public string TargetName;
		private UIntPtr file_index;
		public ulong FileIndex {
			get {
				return (ulong) file_index;
			}
			set {
				file_index = new UIntPtr (value);
			}
		}
		private UIntPtr files_total;
		public ulong FilesTotal {
			get {
				return (ulong) files_total;
			}
			set {
				files_total = new UIntPtr (value);
			}
		}
		public long BytesTotal;
		public long FileSize;
		public long BytesCopied;
		public long TotalBytesCopied;
		public string DuplicateName;
		public int DuplicateCount;
		public bool TopLevelItem;
		private IntPtr _reserved1;
		private IntPtr _reserved2;

		public static Gnome.Vfs.XferProgressInfo Zero = new Gnome.Vfs.XferProgressInfo ();

		public static Gnome.Vfs.XferProgressInfo New(IntPtr raw) {
			if (raw == IntPtr.Zero) {
				return Gnome.Vfs.XferProgressInfo.Zero;
			}
			Gnome.Vfs.XferProgressInfo self = new Gnome.Vfs.XferProgressInfo();
			self = (Gnome.Vfs.XferProgressInfo) Marshal.PtrToStructure (raw, self.GetType ());
			return self;
		}

		private static GLib.GType GType {
			get { return GLib.GType.Pointer; }
		}
#endregion
	}
}
