// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace Gnome.Vfs {

	using System;

#region Autogenerated code
	public enum XferProgressStatus {

		Ok,
		Vfserror = 1,
		Overwrite = 2,
		Duplicate = 3,
	}
#endregion
}
