// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace Gnome.Vfs {

	using System;

#region Autogenerated code
	public enum XferPhase {

		PhaseInitial,
		CheckingDestination,
		PhaseCollecting,
		PhaseReadytogo,
		PhaseOpensource,
		PhaseOpentarget,
		PhaseCopying,
		PhaseMoving,
		PhaseReadsource,
		PhaseWritetarget,
		PhaseClosesource,
		PhaseClosetarget,
		PhaseDeletesource,
		PhaseSetattributes,
		PhaseFilecompleted,
		PhaseCleanup,
		PhaseCompleted,
		NumPhases,
	}
#endregion
}
