// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace Gnome.Vfs {

	using System;

#region Autogenerated code
	public enum XferOverwriteAction {

		Abort,
		Replace = 1,
		ReplaceAll = 2,
		Skip = 3,
		SkipAll = 4,
	}
#endregion
}
