// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace Gnome.Vfs {

	using System;

#region Autogenerated code
	public enum XferErrorAction {

		Abort,
		Retry = 1,
		Skip = 2,
	}
#endregion
}
