name: Ubuntu

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    
    - name: Install dependencies
      run: |
        sudo apt update -qq > /dev/null
        sudo apt install -qq automake libtool intltool nuget > /dev/null
        sudo apt install -qq libgtk2.0-dev libglib2.0-dev liblcms2-dev libjpeg-dev > /dev/null
        sudo apt install -qq adwaita-icon-theme > /dev/null
        sudo apt install -qq libgtk2.0-cil-dev libglib2.0-cil-dev libgio2.0-cil-dev > /dev/null
        sudo apt install -qq gtk-sharp2-gapi libgtk-sharp-beans2.0-cil-dev > /dev/null
        mono --version
    
    - name: Autogen
      run: ./autogen.sh --enable-tests
    
    - name: Make
      run: make
    
    - name: Make Tests
      run: make test

    
    - name: Run Infer#      
      uses: microsoft/infersharpaction@v0.2
      id: runinfersharp
      with:
        binary-path: bin

    - name: Infer# analysis results
      run: echo "${{ steps.runinfersharp.outputs.results }}"
